### ISSUE TITLE
mpd播放没有进度条显示，一首歌播放完成不会切换下一首

### ISSUE THREAD

**Issue by leeh11** [shaonianzhentan/ha_cloud_music#1]
你好，我用的ha版本是：
Home Assistant 2022.10.5
Supervisor 2022.10.2
前端版本： 20221010.0 - latest

mpd在另一台设备上，自定义端口号为：8600

我先尝试在集成里mpd host 配置：192.168.1.11:8600，但是播放没有反应，提示mpd host不存在（貌似）

然后我就在configuration.yaml里配置了
edia_player:
  - platform: mpd
    name: 卧室音乐播放器
    host: 192.168.1.11
    port: 8600

然后云音乐可以播放了，播放内容是网易云我收藏的歌单。但是出现的问题是没办法自动切换下一首，卡片视图显示如下
<img width="571" alt="image" src="https://user-images.githubusercontent.com/24563847/202453517-71518e5f-3a33-416b-8d12-0945174968ee.png">
进度条不会走而且没有时间显示。

云音乐界面进度条可以走动，但是显示的也是错误的，每次刷新都是从0开始。
<img width="1161" alt="image" src="https://user-images.githubusercontent.com/24563847/202454217-aa4cd188-2d7f-449d-9e30-d09c22f1e9a3.png">

我查看了日志界面和配置下面的home-assistant.log文件，都没有相关的log输出。是不是我看log的姿势不对，烦请告知。

问题如上，请帮忙分析一下，不吝感激！

**Comment by MageDelfador** [comment]
我也遇到了，播放歌单时无法自动播放下一首，但有极少数的情况可以自动放出下一首。同样没有日志。
进度条有显示但无法跳转，左下角提示`调用服务 media_player/media_seek 失败。 extra keys not allowed @ data['position']`
我没有用mpd，应该跟mpd本身关系不大

**Comment by shaonianzhentan** [comment]
旧版已经停止维护，可以使用新版MPD云音乐插件
https://github.com/shaonianzhentan/cloud_music_mpd

**Comment by leeh11** [comment]
> 旧版已经停止维护，可以使用新版MPD云音乐插件
> https://github.com/shaonianzhentan/cloud_music_mpd

请问这个mpd插件是单独使用还是要配合 ha_cloud_music使用，目前我两个都装上了，但是云音乐里选择播放器界面找不到『云音乐MPD播放器』

<img width="532" alt="image" src="https://user-images.githubusercontent.com/24563847/202850899-6e0cdc42-c793-4b31-adcf-685d7a6eb725.png">

云音乐MPD播放器我也添加卡片了界面如下：

<img width="564" alt="image" src="https://user-images.githubusercontent.com/24563847/202850956-49e264d5-0433-44ae-805a-cc4d2774c68f.png">

没有播放列表和网易云相关账号绑定入口。

**Comment by shaonianzhentan** [comment]
需要和新版云音乐配合使用

云音乐插件主要提供资源，`云音乐MPD播放器`在浏览媒体中，可读取到音乐信息然后播放

**Comment by leeh11** [comment]
> 需要和新版云音乐配合使用
> 
> 云音乐插件主要提供资源，`云音乐MPD播放器`在浏览媒体中，可读取到音乐信息然后播放

我的云音乐MPD播放器点开 浏览媒体 一直在转圈圈，刷不出来播放列表。

**Comment by shaonianzhentan** [comment]
> > 需要和新版云音乐配合使用
> > 云音乐插件主要提供资源，`云音乐MPD播放器`在浏览媒体中，可读取到音乐信息然后播放
> 
> 我的云音乐MPD播放器点开 浏览媒体 一直在转圈圈，刷不出来播放列表。

云音乐插件没用最新版？

**Comment by leeh11** [comment]
> > > 需要和新版云音乐配合使用
> > > 云音乐插件主要提供资源，`云音乐MPD播放器`在浏览媒体中，可读取到音乐信息然后播放
> > 
> > 
> > 我的云音乐MPD播放器点开 浏览媒体 一直在转圈圈，刷不出来播放列表。
> 
> 云音乐插件没用最新版？

我就是在这个项目点击的Add Integration添加的插件
manifest文件里边版本号是1.0
<img width="593" alt="image" src="https://user-images.githubusercontent.com/24563847/203722293-d533c103-44f3-4f45-b5a5-ba14a97c0892.png">

**Comment by shaonianzhentan** [comment]
你用的是旧版本

**Comment by leeh11** [comment]
可以了，感谢！我手动删除custom_components下面的ha_cloud_music再重新安装就可以了。
