### ISSUE TITLE
登录不上网易云账号

### ISSUE THREAD

**Issue by Dengliaohui** [shaonianzhentan/ha_cloud_music#12]
![图片](https://user-images.githubusercontent.com/108753806/206749020-8010ac54-6ae6-4177-aafd-277985fc0286.png)
那位大师知道怎么解决的，麻烦说下

**Comment by shaonianzhentan** [comment]
这是接口服务的问题，你需要自行部署接口到本地，然后定期更新升级即可

**Comment by Dengliaohui** [comment]
可以讲下怎么布署，或推下教材给我吗

**Comment by shaonianzhentan** [comment]
为啥不认真看文档？🤔
![image](https://user-images.githubusercontent.com/5294022/207210609-04123ba1-9e0d-40a4-bcc7-1ceb323480ba.png)

**Comment by Dengliaohui** [comment]
你说的是api接口的问题啊

**Comment by shaonianzhentan** [comment]
> 你说的是api接口的问题啊

因为我不知道你怎么部署的接口，部署的是哪个版本

只知道你登录不上，所以我判定是接口的问题（这个问题大多数都是网络或代理问题，情况很复杂）

然后接口相关的问题，需要你自己去那个接口的项目找解决方案，图中的链接就是那个项目的开源地址

**Comment by j96745** [comment]
@shaonianzhentan 你好，我在本地通过docker和vercel上也都部署了一下，网页服务能跑起来。但也发现同样的问题无法登录。麻烦您给帮忙分析分析。感谢！
[image](https://user-images.githubusercontent.com/76676269/210075184-5a1b201a-e224-43d4-b621-8d18ebba79b7.png)
![image](https://user-images.githubusercontent.com/76676269/210075335-c03ee56d-6474-4592-b18c-a17997a449ba.png)

**Comment by delta088** [comment]
您好，我也遇到了同样的问题，本地测试后发现要求验证才能通过，请问cookie在本地的哪个文件里存的？我想直接把cookie copy进去。 谢谢。

**Comment by delta088** [comment]
最近用账号密码登录会遇到云盾问题，请问可以开发验证码或二维码登录吗 谢谢

**Comment by shaonianzhentan** [comment]
> 最近用账号密码登录会遇到云盾问题，请问可以开发验证码或二维码登录吗 谢谢

文件路径：`.storage/cloud_music.userinfo`

在网易云音乐的网页中，按F12打开控制台，找到对应的数据

然后替换掉uid和被抹掉的值就好了
![image](https://user-images.githubusercontent.com/5294022/216382871-9f76d31e-dd20-498d-85af-1573b5fbd7ac.png)

**Comment by ww2435240** [comment]
> > 最近用账号密码登录会遇到云盾问题，请问可以开发验证码或二维码登录吗 谢谢
> 
> 文件路径：`.storage/cloud_music.userinfo`
> 
> 在网易云音乐的网页中，按F12打开控制台，找到对应的数据
> 
> 然后替换掉uid和被抹掉的值就好了 ![image](https://user-images.githubusercontent.com/5294022/216382871-9f76d31e-dd20-498d-85af-1573b5fbd7ac.png)

2023.2.3版本  /config/.storage文件夹下没有cloud_music.userinfo文件。
用网页登陆   http://接口IP:3000/login?email=XXXX@163.com&password=XXXX]
返回
{"code":-462,"data":{"actionCode":"1102401","verifyType":50,"verifyId":1,"verifyUrl":"","blockText":"网络太拥挤，请稍候再试。","verifyToken":null,"btnText":null,"orpheusUrl":null,"frontRuleIds":[1102401],"params":{"event_id":"00332244015021187084","sign":"f76d3e30b1772b8120258ae9a83b377a"},"url":null},"message":"网络太拥挤，请稍候再试。"}

是不是现在手机号和邮箱都无法登陆了？

**Comment by shaonianzhentan** [comment]
是你自己部署的接口服务有问题，如果经常不维护，就会这样，我也不知道为啥（可能是网易的相关接口变动了，代码没适配？）

一般解决方法
1. 升级接口服务 `自己拉取最新的接口服务代码重新部署`
2. 配置代理 `有时间会因为请求来源问题触发校验机制`
3. 手动配置cookie `只有登录成功后才会产生，初次使用请手动创建文件`
4. 付费使用我部署维护的 `我会定期检查接口是否异常，然后排查处理`

**Comment by yzlnew** [comment]
API 的文档里面已经不建议用密码认证，直接二维码认证之后手动配置 cookie 即可。

**Comment by shaonianzhentan** [comment]
已支持扫码登录
