### ISSUE TITLE
这个新版云音乐插件和cloud_music_mpd里最新的是能一起用的吗？

### ISSUE THREAD

**Issue by hostank** [shaonianzhentan/ha_cloud_music#13]
您好，
我的Home Assistant是2022.12.5版，ha_cloud_music最新版，cloud_music_mpd最新版
我单独装新版云音乐的插件，用媒体控制卡片是可以正常播放、暂停、下一首之类的操作的，但是我装上cloud_music_mpd之后，mpd用媒体控制卡片点播放什么的都会报错，请问是不是现在的这个mpd是适配之前那个4.7.4的云音乐插件的？

另外这个最新的插件，点开卡片的属性之后，下面没有列表、播放源、搜索那些东西了，是原本就是这样的吗？

![1](https://user-images.githubusercontent.com/120378959/207841051-6cff01be-318e-4603-8540-2617f8369dc4.PNG)

**Comment by shaonianzhentan** [comment]
cloud_music_mpd必须搭配新版云音乐使用，安装后可以分别独立使用

云音乐播放器可通过配置DLNA播放器使用
cloud_music_mpd则是一个单独的MPD播放器，使用了云音乐的音乐资源而已

**Comment by shaonianzhentan** [comment]
另外这个插件处于测试版，功能还有待完善，目前是以HA官方的界面样式为主，暂无额外的操作界面

**Comment by hostank** [comment]
您说的这个必须搭配新版云音乐是说的这个测试版插件还是另一4.7.4的那个呢？

**Comment by shaonianzhentan** [comment]
![image](https://user-images.githubusercontent.com/5294022/208235376-58db62ef-1e26-44dd-9156-265b8fac17be.png)
