### ISSUE TITLE
此集成不支持通过 UI 配置。如果您是从 Home Assistant 网站点击链接前来，请确保您运行的是最新版本的 Home Assistant

### ISSUE THREAD

**Issue by xinmans** [shaonianzhentan/ha_cloud_music#15]
点了add homeassistant之后提示这个

**Comment by shaonianzhentan** [comment]
安装成功后，需要重新启动HomeAssistant，然后再刷新一下浏览器页面

如果执行以上步骤还未成功，请打开自定义组件目录检查是否文件是否安装成功

**Comment by buailove** [comment]
configuration.yaml

homeassistant:
  customize: !include customize.yaml
customize.yaml

media_player.yun_yin_le:
  media_player: 
    - media_player.源实体1
    - media_player.源实体2
    - media_player.源实体3
    这个具体怎么配置呢？本人小白，这个源实体是指的什么

**Comment by 643406834** [comment]
> 

homeassisatnt的播放器

**Comment by 643406834** [comment]
> configuration.yaml
> 
> homeassistant: customize: !include customize.yaml customize.yaml
> 
> media_player.yun_yin_le: media_player: - media_player.源实体1 - media_player.源实体2 - media_player.源实体3 这个具体怎么配置呢？本人小白，这个源实体是指的什么

homeassisatnt的播放器
