### ISSUE TITLE
二维码扫码登录feature

### ISSUE THREAD

**Issue by jwxa** [shaonianzhentan/ha_cloud_music#17]
写了一个demo走通了 自己够用
https://github.com/jwxa/ha_cloud_music/commit/1034152b251edd58a597f27324f9caae884d0145
因为现在直接账号密码登录拦截太厉害了,希望可以加入这个功能
python新手 注释都写了

替换了原来的login -> qr_login
步骤就是随便输入账密 点击下一步
然后登录窗口阻塞 直接关闭
![image](https://user-images.githubusercontent.com/9533487/221371439-ea9a0a88-bc41-426d-ba1c-dd507adabe93.png)
查看通知栏
![image](https://user-images.githubusercontent.com/9533487/221371454-070b778f-1f3a-42c6-9b59-328daa4d74bd.png)
打开手机扫码
![image](https://user-images.githubusercontent.com/9533487/221371469-b254b916-cf55-4bce-ae85-7cfbb295b55e.png)

成功后会解析cookie写入\.storage\cloud_music.userinfo

**Comment by shaonianzhentan** [comment]
我有时间考虑一下

**Comment by shaonianzhentan** [comment]
已支持扫码登录

**Comment by cstackess** [comment]
> 

怎么触发扫码登录？输入用户名、密码提示“Unknown error occurred”
