### ISSUE TITLE
更新了2023.3.5版本之后出现播放问题

### ISSUE THREAD

**Issue by Rookie9512** [shaonianzhentan/ha_cloud_music#19]
选择歌曲之后不会播放，并且歌曲总时长一直是0

**Comment by Dengliaohui** [comment]
我的也是

**Comment by shaonianzhentan** [comment]
如果是从4.x版本升级，请重新配置，新版不兼容之前的所有配置

**Comment by Rookie9512** [comment]
> 如果是从4.x版本升级，请重新配置，新版不兼容之前的所有配置

我是直接用的新版云音乐，没有用旧版本的，在hacs自定义了库用hacs下载添加的，然后提示更新后直接更新到这个版本，然后出现这个问题，看日志是一直在获取这首歌曲的信息，api应该是不存在问题，我手动调没有问题，api部署在vercel

**Comment by shaonianzhentan** [comment]
> > 如果是从4.x版本升级，请重新配置，新版不兼容之前的所有配置
> 
> 我是直接用的新版云音乐，没有用旧版本的，在hacs自定义了库用hacs下载添加的，然后提示更新后直接更新到这个版本，然后出现这个问题，看日志是一直在获取这首歌曲的信息，api应该是不存在问题，我手动调没有问题，api部署在vercel

这个插件你确定是知道怎么使用的吧？并不是安装了就直接可以使用的，需要进行DLNA播放器关联配置

**Comment by SmileIOT** [comment]
> > > 如果是从4.x版本升级，请重新配置，新版不兼容之前的所有配置
> > 
> > 
> > 我是直接用的新版云音乐，没有用旧版本的，在hacs自定义了库用hacs下载添加的，然后提示更新后直接更新到这个版本，然后出现这个问题，看日志是一直在获取这首歌曲的信息，api应该是不存在问题，我手动调没有问题，api部署在vercel
> 
> 这个插件你确定是知道怎么使用的吧？并不是安装了就直接可以使用的，需要进行DLNA播放器关联配置

可不可以讲一下如何进行DLNA播放器关联配置，貌似大家都卡在这里了，谢谢！
