### ISSUE TITLE
configuration.yaml和customize.yaml具体如何配置

### ISSUE THREAD

**Issue by buailove** [shaonianzhentan/ha_cloud_music#20]
configuration.yaml和customize.yaml具体如何配置，源实体是什么？

**Comment by shaonianzhentan** [comment]
建议关注公众号，学习一下HomeAssistant基础知识

另外B站上也有视频介绍，可以持续关注了解相关内容

**Comment by buailove** [comment]
麻烦问下B站账号是什么？

**Comment by shaonianzhentan** [comment]
> 麻烦问下B站账号是什么？

https://www.bilibili.com/video/BV1S54y1w7i6/

**Comment by shaonianzhentan** [comment]
已改为在选项中关联配置
