### ISSUE TITLE
登陆成功无法正常播放进度条没有变化

### ISSUE THREAD

**Issue by chaosl1996** [shaonianzhentan/ha_cloud_music#23]
<img width="896" alt="image" src="https://user-images.githubusercontent.com/76881956/230911141-e7e0552f-42b0-46c6-b223-82f0b265d077.png">
表现：
点击播放，进度条无变化，完全没有声音

测试内容如下：
1，使用云音乐里面的本地媒体库打开可以正常播放，但在线列表无法正常播放。（应该可以证明DLNA连接配置正常，另外音量正常可以调节）
2，使用Vercel 部署和本地docker部署都试过，均无法正常运行。

版本：2023年4月10日初次部署

**Comment by shaonianzhentan** [comment]
如果FM电台也能播放的话，应该网段隔离的问题

这里填上外网链接，如果没有就填当前局域网里访问的地址，**例如 `http://192.168.0.11:8123`**

保存之后，再去试试，应该就有声音了
![image](https://user-images.githubusercontent.com/5294022/230924827-f6267ee5-5c73-47dc-8de5-8c3071663d7b.png)

**Comment by chaosl1996** [comment]
卧槽大佬牛逼啊，完美解决

**Comment by noctiro** [comment]
根据这个issue解决了播放问题

但是要如何解决没有显示进度条呢
