### ISSUE TITLE
安装集成不成功

### ISSUE THREAD

**Issue by titanfox88** [shaonianzhentan/ha_cloud_music#24]
提示无法加载配置向导: {"message":"Invalid handler specified"}，无其他日志输出，请问这是什么情况，谢谢

**Comment by zhangziran** [comment]
同样遇到。hass更新到最新就好了。。。。这算是hass祖传的毛病了向上兼容性不好

**Comment by titanfox88** [comment]
更新了最新的4.6还是一样的提示。

**Comment by shaonianzhentan** [comment]
升级到最新版本，然后确保下载的文件没有缺失
