### ISSUE TITLE
添加后是空白，也没有实体出现，版本是2023.04.0

### ISSUE THREAD

**Issue by style6** [shaonianzhentan/ha_cloud_music#27]
添加后是空白，也没有实体出现，版本是2023.04.0
hacs安装的，也试过用无痕模式，都是空白
![2023422-13016](https://user-images.githubusercontent.com/47061418/233699292-1319ea6f-b9ef-417f-848b-0076ba0b9c55.png)

**Comment by style6** [comment]
清空了原来的.shaonianzhentand的缓存文件可以了，但是登录不了，还有浏览文件哪里是空白的

**Comment by style6** [comment]
![2023422-20657](https://user-images.githubusercontent.com/47061418/233705330-d757ff43-37ee-4991-9307-03a21925acff.png)

**Comment by shaonianzhentan** [comment]
你使用的这个插件是老版本，已经停止更新了

**Comment by style6** [comment]
> 你使用的这个插件是老版本，已经停止更新了

我装的是ha_cloud_music，应该是新的吧，cloud_music才是旧的吧

**Comment by style6** [comment]
找到问题了，原来用的https://vercel.com/dashboard这个搭建，现在换本地搭建就可以了

**Comment by lausonus** [comment]
我也是用vercel搭建的，也是登陆不了，大哥怎么本地搭建呢
