### ISSUE TITLE
搜索播放如果支持云盘内或者歌单内搜索会不会是个新思路

### ISSUE THREAD

**Issue by zhangziran** [shaonianzhentan/ha_cloud_music#30]
网易云现在版权越来越少，想解决要不继续对接第三方（但是这样可能又会增加工作量)，要不自己传云盘调用。

**Comment by shaonianzhentan** [comment]
这个功能已经实现了
正常情况下如果音乐是VIP或没有版权，会优先去云盘搜索，如果找不到则会到第三方网站抓取

考虑到网易的音乐大部分是翻唱，所以查找的结果可能会有偏差

**Comment by zhangziran** [comment]
> 

如果账号是vip，默认播放的哪个音质啊

**Comment by shaonianzhentan** [comment]
> > 
> 
> 如果账号是vip，默认播放的哪个音质啊

默认MP3 320kbps，如果设备支持更高音质，可以尝试自己修改代码
