### ISSUE TITLE
新版集成登陆失败

### ISSUE THREAD

**Issue by lausonus** [shaonianzhentan/ha_cloud_music#32]
最新版在HA集成里面点开云音乐插件登陆失败，F12显示
500 Internal Server Error
Server got itself in trouble

**Comment by lausonus** [comment]
版本：2023.3.30

**Comment by shaonianzhentan** [comment]
要不你扫码登录试试？

**Comment by lausonus** [comment]
我看了公众号的文章，不知道为什么，我这个没扫码登陆。安装的是https://github.com/shaonianzhentan/ha_cloud_music 正常应该是新版才对

**Comment by bossben8** [comment]
台灣手機號無法在集成雲音樂登入,顯示登入失敗....

**Comment by lausonus** [comment]
![1微信截图_20230505224116](https://user-images.githubusercontent.com/14193597/236489936-93460180-3f77-4ed1-979c-39d1aface457.png)
尝试扫码登陆，但是点入这里提示“媒体浏览错误”

**Comment by lausonus** [comment]
![微信截图_20230505234917](https://user-images.githubusercontent.com/14193597/236506409-86e6eb91-e21b-4439-9a4b-c1b1d3f95c7b.png)
点击媒体一直转动

**Comment by lausonus** [comment]
已解决，完成处理。用邮箱也可以登陆了。开始是用Vercel部署的API，后面换成了国内部署的API，媒体可以访问、也可以登陆，也能正常播放，感谢大佬
