### ISSUE TITLE
thewind.xyz 无法访问

### ISSUE THREAD

**Issue by llgxdnn** [shaonianzhentan/ha_cloud_music#34]
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='thewind.xyz', port=443): Max retries exceeded with url: /music/api/search (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f99ebd1b0>: Failed to establish a new connection: [Errno -2] Name does not resolve'))

**Comment by shaonianzhentan** [comment]
安装 main 分支
