### ISSUE TITLE
请问在nodered中怎么自动设置指定播放的歌单呢？比如日推

### ISSUE THREAD

**Issue by ray5378** [shaonianzhentan/ha_cloud_music#35]
可以正常播放了，但是有时候播放要手动选择歌单，请问在nodered中怎么自动设置指定播放的歌单呢？比如日推

登录后播放

每日推荐 cloudmusic://163/my/daily

应该怎么设置

**Comment by shaonianzhentan** [comment]
可以使用官方的播放媒体服务，如果不了解可以去公众号查看详细使用教程
