### ISSUE TITLE
无法加载配置向导: {"message":"Invalid handler specified"}

### ISSUE THREAD

**Issue by pythonLiNM** [shaonianzhentan/ha_cloud_music#37]
最新版，配置集成失败
![image](https://github.com/shaonianzhentan/ha_cloud_music/assets/50547107/33f728c3-f438-46d6-9271-c0826f52b7d0)

**Comment by mobyoung** [comment]
出现同样问题

**Comment by leungyuan** [comment]
same

**Comment by robbbit** [comment]
同样的问题，有人解答嘛？

**Comment by ettingshausen** [comment]
+1

**Comment by kinaxng** [comment]
+1

**Comment by stcwl** [comment]
同样的错误，请问有解决办法吗

**Comment by shaonianzhentan** [comment]
由于国内网络问题，可能导致插件未能完整下载，或者依赖无法正常安装。建议重新下载并安装插件。

**Comment by liguobao** [comment]
看起来是个package路径问题。

2023-12-22 00:51:33.528 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration ha_cloud_music: No module named 'custom_components.ha_cloud_music'

日志里面的错误信息。

**Comment by xiesimple** [comment]
同样出现这个问题，如何解决
