### ISSUE TITLE
media_duration: 0

### ISSUE THREAD

**Issue by bg3ahc** [shaonianzhentan/ha_cloud_music#39]
DLNA模式播放时，get不到歌曲总时长，导致没有进度条和不能自动下一曲，是api解析歌曲url的问题吗，手动在地址栏输入API的地址就可以获取media_duration信息。

**Comment by shaonianzhentan** [comment]
一般这种情况，通常是你的DLNA设备不支持此功能

**Comment by bg3ahc** [comment]
哦，小爱音箱就可以，sonos反而get不到
