### ISSUE TITLE
音量可以正常设置，但读取时始终为1

### ISSUE THREAD

**Issue by MageDelfador** [shaonianzhentan/ha_cloud_music#4]
设置音量确实可以改变音量，但属性volume_level始终为1

**Comment by MageDelfador** [comment]
测试了一下，云音乐设置音量可以保存了，但不会主动跟播放设备同步。
也就是说在播放设备上更改音量不会显示在云音乐上，并且重启homeassistant后云音乐的音量会还原成1

**Comment by shaonianzhentan** [comment]
> 测试了一下，云音乐设置音量可以保存了，但不会主动跟播放设备同步。 也就是说在播放设备上更改音量不会显示在云音乐上，并且重启homeassistant后云音乐的音量会还原成1

有些DLNA设备的音量不准，同步过来没啥用

**Comment by MageDelfador** [comment]
确实不是很重要，问题不大。
