### ISSUE TITLE
求助 - 如何设置那个音箱作为播放器？

### ISSUE THREAD

**Issue by shawn82** [shaonianzhentan/ha_cloud_music#40]
我在configuration.yaml内加入以下代码，依然不出现播放器选择
homeassistant:
  customize:
    media_player.yun_yin_le:
      media_player:
        - media_player.8d3cd512_99a4cead

recorder:
  exclude:
    entities:
      - media_player.yun_yin_le

每次只能在云音乐的配置设定内选择“关联媒体播放器”来选择

**Comment by shaonianzhentan** [comment]
已经放弃了这种旧的配置方式，请关注微信公众号查看最新使用教程

**Comment by tianjiao96176** [comment]
> 已经放弃了这种旧的配置方式，请关注微信公众号查看最新使用教程

微信公众号是多少？

**Comment by shaonianzhentan** [comment]
> > 已经放弃了这种旧的配置方式，请关注微信公众号查看最新使用教程
> 
> 微信公众号是多少？

项目文档底部有二维码
