### ISSUE TITLE
播放音乐报错，播放电台正常

### ISSUE THREAD

**Issue by anxms** [shaonianzhentan/ha_cloud_music#41]
Logger: aiohttp.server
Source: /usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py:403
First occurred: 09:48:34 (1 occurrences)
Last logged: 09:48:34

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 332, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "aiohttp/_http_parser.pyx", line 557, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadHttpMessage: 400, message:
  Expected HTTP/:

    b'GET /cloud_music/url?id=2099601478 song=%E5%81%87%E8%AE%BE singer=%E9%83%91%E6%B6%A6%E6%B3%BD source=3 HTTP/1.1\r'
                                         ^
ha已经设置外网连接地址

**Comment by shaonianzhentan** [comment]
已修复

**Comment by sloganlau** [comment]
2023.12.19 仍有该情况，没有报错信息。问题解决，未配置外网链接地址
