### ISSUE TITLE
ha更新2024.1后云音乐无法使用

### ISSUE THREAD

**Issue by Gzzloveyyt** [shaonianzhentan/ha_cloud_music#44]
ha更新2024.1后云音乐无法使用，望修复！

**Comment by xyzhangxin** [comment]
+1，感谢大佬

**Comment by SmileIOT** [comment]
+1

**Comment by dxh000130** [comment]
+1

**Comment by sloganlau** [comment]
报错信息如下：
`2024-01-16 09:06:28.801 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140398645351872] Error handling message: Unknown error (unknown_error) Simon from 172.17.0.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/media_player/__init__.py", line 1298, in websocket_browse_media
    if MediaPlayerEntityFeature.BROWSE_MEDIA not in player.supported_features:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'int' is not iterable`

**Comment by sloganlau** [comment]
HA回退到2023.8.4版本，不报错，工作正常

**Comment by JTRoger** [comment]
应该是新版core有些字段对象改了

**Comment by shaonianzhentan** [comment]
已修复
