### ISSUE TITLE
小爱音响DLNA的问题

### ISSUE THREAD

**Issue by Gzzloveyyt** [shaonianzhentan/ha_cloud_music#45]
不知道为啥，大佬不愿意测试 @qqdwtypm 大佬的方法可以解决该问题的，该大佬的方法可以解决小爱音响DLNA无法自动切换下一首的问题，大佬让我自行fork一份，是不是解决该问题更好呢？ #22

**Comment by shaonianzhentan** [comment]
由于我无法进行测试，才建议fork一份代码自行修改，以适应自己的设备。

> 目前我的小度音箱DLNA功能、Windows Media Player DLNA功能以及电视等DLNA服务都可以正常工作。
