### ISSUE TITLE
播放歌单的时候，歌单内歌曲不能自动连播

### ISSUE THREAD

**Issue by MageDelfador** [shaonianzhentan/ha_cloud_music#5]
播放整个歌单的时候，云音乐播放完第一首歌之后，不会自动切换到下一首。需要手动点击下一首才可以。

**Comment by uncle-wong** [comment]
我好像没有这个问题，当然我也不会搜索歌曲，我测试的歌单是，媒体，榜单，飙升榜，我下面关联的那几个都装了。新版界面跟老版不同，我不知道你的是否跟我一样。

**Comment by MageDelfador** [comment]
> 我好像没有这个问题，当然我也不会搜索歌曲，我测试的歌单是，媒体，榜单，飙升榜，我下面关联的那几个都装了。新版界面跟老版不同，我不知道你的是否跟我一样。

试了下飙升榜，仍然不会自动连播。关联的那几个项目我没装。

**Comment by shaonianzhentan** [comment]
> 播放整个歌单的时候，云音乐播放完第一首歌之后，不会自动切换到下一首。需要手动点击下一首才可以。

首先你得确定源播放是否有总时长`media_duration`和播放进度`media_position`这两个属性

云音乐是通过这两个属性判断是否应该自动跳转到下一曲

**Comment by MageDelfador** [comment]
看了下我的播放器的代码，它播放完成后`media_duration`和`media_position`这两个属性会变成None。
我研究了下homeassistant官方的集成vlc和mpd的代码，发现它们的这两个属性不会变成None。
所以，应该是我的播放器的问题，改了下我的播放器的代码，问题解决。
