### ISSUE TITLE
HA提示储存库不符合规范

### ISSUE THREAD

**Issue by 865258951** [shaonianzhentan/ha_cloud_music#60]
<Plugin shaonianzhentan/ha_cloud_music> Repository structure for 2024.8.9 is not compliant
![image](https://github.com/user-attachments/assets/da525004-5c13-4cb0-93bc-5f4f55b1bf50)

**Comment by shaonianzhentan** [comment]
应该是你的Type选择错误导致的

**Comment by 865258951** [comment]
原来如此，重新选择后可以正常添加了
感谢
