### ISSUE TITLE
云音乐找不到播放源

### ISSUE THREAD

**Issue by airwb** [shaonianzhentan/ha_cloud_music#7]
升级新版后，找不到播放源，请问新版的播放源怎么设置

**Comment by shaonianzhentan** [comment]
需要手动配置自定义实体属性
![image](https://user-images.githubusercontent.com/5294022/202861850-eb0a87ef-95b1-4e08-b7e7-c08c7b91fd1a.png)

**Comment by nightjoyip** [comment]
请问若要使用网页播放器，customize.yaml应该怎么写？

**Comment by nightjoyip** [comment]
> 需要手动配置自定义实体属性 ![image](https://user-images.githubusercontent.com/5294022/202861850-eb0a87ef-95b1-4e08-b7e7-c08c7b91fd1a.png)

**Comment by nightjoyip** [comment]
> 需要手动配置自定义实体属性 ![image](https://user-images.githubusercontent.com/5294022/202861850-eb0a87ef-95b1-4e08-b7e7-c08c7b91fd1a.png)

请问若要使用网页播放器，customize.yaml应该怎么写？

**Comment by shaonianzhentan** [comment]
> > 需要手动配置自定义实体属性 ![image](https://user-images.githubusercontent.com/5294022/202861850-eb0a87ef-95b1-4e08-b7e7-c08c7b91fd1a.png)
> 
> 请问若要使用网页播放器，customize.yaml应该怎么写？

不支持网页播放
