### ISSUE TITLE
手动将文件下载复制到custom_components并重启多次后，在集成里搜索不到云音乐

### ISSUE THREAD

**Issue by shenslink** [shaonianzhentan/ha_cloud_music#8]
RT，谢谢~

**Comment by shaonianzhentan** [comment]
请检查组件文件目录结构，如确定无误，请附上错误日志

**Comment by shenslink** [comment]
![Screenshot_20221125_193109_Home Assistant](https://user-images.githubusercontent.com/116306402/203976598-9d668cfd-f79c-4ba6-a48d-3972d3251553.jpg)
感谢回复！文件目录如图，因为在集成里搜索不到，所以也不知道到哪看错误日志。

**Comment by shaonianzhentan** [comment]
配置/系统/日志
