### ISSUE TITLE
请问这个新版本云音乐的接口怎么配置的？

### ISSUE THREAD

**Issue by mrhanCH** [shaonianzhentan/ha_cloud_music#9]
ha新人小白，请问这个新版本云音乐的接口怎么配置的？是在配置文件中配置apiurl还是需要安装老版本的云音乐插件后使用呢？

**Comment by shaonianzhentan** [comment]
仅支持集成安装，安装时会提示配置

**Comment by mrhanCH** [comment]
安装和配置问题已解决，现在有一个问题就是，播放源配置的是小爱音箱的实体ID，但是云音乐播放音乐时音箱没有播放，而且云音乐下面进度条不会动，当我调整云音乐插件的声音大小时，音箱是可以跟随调整的。还有就是云音乐点击播放后，音箱实体的历史记录我看是由播放自动变为了暂停。具体请看下方，感谢回复。

是否是小爱音箱不能作为播放源来使用？

pi@raspberrypi:~/homeassistant $ cat customize.yaml 
media_player.yun_yin_le:
  media_player: media_player.xiaomi_lx5a_a5f2_play_control

下面是云音乐的历史记录：
2022年11月25日
变为 正在播放 由服务触发 media_player.media_play
22:46:08 - 10秒钟前 - MrHan

下面是音箱的历史记录：
变为 已暂停 由服务触发 media_player.media_play
22:44:50 - 8分钟前
变为 正在播放 由服务触发 media_player.media_play
22:44:46 - 8分钟前

**Comment by shaonianzhentan** [comment]
小爱音箱并不支持自定义播放链接
